:-(make_file_path(A,B,C,D),','(string_constant(E),','(atom_concat(A,E,F),','(atom_concat(F,B,G),','(atom_concat(G,E,H),atom_concat(H,C,D)))))).
:-(process_lists(A,B,C,D,E),','(append(A,B,F),','(string_concat(C,D,G),append(F,[G],E)))).
employee(john,developer,2020).
employee(jane,manager,2018).
employee(bob,tester,2021).
:-(senior_employee(A,B,C),','(employee(A,B,C),<(C,2020))).
:-(format_employee(A,B,C,D),','(string_constant(E),','(string_concat(A,E,F),','(string_concat(F,B,G),','(string_constant(H),','(string_concat(G,H,I),','(string_concat(I,C,J),','(string_constant(K),string_concat(J,K,D))))))))).
filter_recent_employees([],A,[]).
:-(filter_recent_employees([employee(A,B,C)|D],E,[A|F]),','(>=(C,E),filter_recent_employees(D,E,F))).
:-(filter_recent_employees([A|B],C,D),filter_recent_employees(B,C,D)).
