% Generated by Prolog to Starlog Converter
% Date/Time: 2025-07-02 00:25:18 UTC
% User: luciangreenPlease
% Compression applied where possible

test_is(A,B):-A is B+5.
test_equals(A,B):-A=B.
test_wrap(A,B):-B is wrap(A).
test_unwrap(A,B):-B is unwrap(A).
test_head_tail(A,B,C):-B is head(A),C is tail(A).
test_member_delete(A,B,C):-A is member_1(B),C is delete(A,B).
test_string_number(A,B):-B is string_to_number(A).
test_random(A,B):-B is random(A).
test_length(A,B):-B is length_1(A).
test_ceiling(A,B):-B is ceiling(A).
test_date(A):-A is date.
test_sqrt(A,B):-B is sqrt(A).
test_round(A,B):-B is round(A).
test_findall(A,B):-B is findall(C,between(1,A,C)).
test_string_from_file(A,B):-B is string_from_file(A).
test_maplist(A,B):-B is maplist(plus(1),A).
test_sort(A,B):-B is sort(A).
test_intersection(A,B,C):-C is intersection(A,B).
test_read_string(A,B):-open(A,read,C),B is read_string(C,1000,D,E),close(C).
test_atom_string(A,B):-B is atom_string(A).
test_call(A):-member(A,[1,2,3]).
complex_test(A,B,C):-B is string_to_number(A),D is sqrt(B),E is ceiling(D),F is round(E),G is random(F),C is number_string(G).
nested_test(A,B):-C is length_1(A),D is sort(A),E is maplist(sqrt,D),B is reverse(E).
