% Generated by Prolog to Starlog Converter
% Date/Time: 2025-07-02 00:25:18 UTC
% User: luciangreenPlease
% Compression applied where possible

test_term_to_atom(A,B):-term_to_atom(A,B).
test_number_string(A,B):-B is number_string(A).
test_maplist(A,B):-B is maplist(atom_chars,A).
test_foldl(A,B):-foldl(atom_concat,A,"",B).
test_string_chars(A,B):-B is string_chars(A).
g(A,B):-A is f,B=A.
test_compression(A,B,C,D,E):-C is A:B,E is •(C,D).
test_quotes(A,"Quoted string",B):-B is A:"Quoted string".
