% Generated by Prolog to Starlog Converter
% Date/Time: 2025-07-02 00:25:18 UTC
% User: luciangreenPlease
% Compression applied where possible

fact1.
fact2(a,b).
test_simple(A,B):-A is &([1],[2]),B is &(A,[3]).
test_strings(A,B,C):-A is •("Hello"," "),B is •(A,"world!"),C is string_length(B).
test_builtin(A,B):-A is number_string(42),B is A:" is the answer".
test_nested(A,B):-C is length_1(A),(C>5->sort(A,B);reverse(A,B)).
test_quotes(single_quoted,"double quoted").
